// <auto-generated />
using System;
using AcountManagement.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcountManagement.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AcountContext))]
    [Migration("20220321163527_ignorName")]
    partial class ignorName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcountManagement.Domain.Acount.Agg.Acount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserPhoto")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Username")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Acounts");
                });

            modelBuilder.Entity("AcountManagement.Domain.Rol.Agg.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("AcountManagement.Domain.Acount.Agg.Acount", b =>
                {
                    b.HasOne("AcountManagement.Domain.Rol.Agg.Rol", "Rol")
                        .WithMany("Acounts")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AcountManagement.Domain.Rol.Agg.Rol", b =>
                {
                    b.OwnsMany("AcountManagement.Domain.Rol.Agg.Permission", "Permissions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Code")
                                .HasColumnType("int");

                            b1.Property<long>("RolId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("RolId");

                            b1.ToTable("Permissions");

                            b1.WithOwner("Rol")
                                .HasForeignKey("RolId");

                            b1.Navigation("Rol");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("AcountManagement.Domain.Rol.Agg.Rol", b =>
                {
                    b.Navigation("Acounts");
                });
#pragma warning restore 612, 618
        }
    }
}
